language: cpp

compiler:
  - gcc
  #- clang  soon

#before_install:
#  - rvm use $RVM --install --binary --fuzzy

#before_script:
#  - if [ $TRAVIS_OS_NAME == linux ]; then travis_retry ./configure --llvm-config llvm-config-3.4; fi

script: make libs; make examples; make test

#after_success:
#  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi

branches:
  only:
    - master
#    - 1.8.7
#    - 2.2
#    - /^v\d+\./

notifications:
  email: false
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/9502afd22ca6c8e85fb3
#    on_success: change
#    on_failure: always
#    on_start: always

#env:
#  - RVM=2.0.0 LANG="en_US.UTF-8"

os:
  - linux
  # - osx


